// <auto-generated />
using System;
using AgroProcessing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroProcessing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111151338_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroProcessing.Domain.Entries.BatchOutputAllocation", b =>
                {
                    b.Property<Guid>("BatchOutputAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllocatedProcessingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InputWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutputWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("BatchOutputAllocationId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("PurchaseBatchId");

                    b.ToTable("BatchOutputAllocations");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Farmer", b =>
                {
                    b.Property<Guid>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.FinishedInventory", b =>
                {
                    b.Property<Guid>("FinishedInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseBatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FinishedInventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseBatchId");

                    b.ToTable("FinishedInventories");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingCost", b =>
                {
                    b.Property<Guid>("ProcessingCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.HasKey("ProcessingCostId");

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("ProcessingCosts");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingOutput", b =>
                {
                    b.Property<Guid>("ProcessingOutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalInputWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOutputWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YieldPercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProcessingOutputId");

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("ProcessingOutputs");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingRun", b =>
                {
                    b.Property<Guid>("ProcessingRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Started");

                    b.HasKey("ProcessingRunId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProcessingRuns");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingRunInput", b =>
                {
                    b.Property<Guid>("ProcessingRunInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("InputWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("ProcessingRunInputId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("PurchaseBatchId");

                    b.ToTable("ProcessingRunInputs");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingStage", b =>
                {
                    b.Property<Guid>("ProcessingStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProcessingStageId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("ProcessingStages");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingStageWorker", b =>
                {
                    b.Property<Guid>("ProcessingStageWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProcessingStageId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkedDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("ProcessingStageWorkerId");

                    b.HasIndex("ProcessingStageId");

                    b.HasIndex("WorkerId");

                    b.ToTable("ProcessingStageWorkers");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DryingDaysMax")
                        .HasColumnType("integer");

                    b.Property<int>("DryingDaysMin")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExpectedYieldPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.PurchaseBatch", b =>
                {
                    b.Property<Guid>("PurchaseBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentSettlementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RatePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RawWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Stored");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseBatchId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("ProductId");

                    b.ToTable("PurchaseBatches");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.PurchasePayment", b =>
                {
                    b.Property<Guid>("PurchasePaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PurchaseBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PurchasePaymentId");

                    b.HasIndex("PurchaseBatchId");

                    b.ToTable("PurchasePayments");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.RawInventory", b =>
                {
                    b.Property<Guid>("RawInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseBatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RawInventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseBatchId");

                    b.ToTable("RawInventories");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Sale", b =>
                {
                    b.Property<Guid>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Open");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.SaleBatchAllocation", b =>
                {
                    b.Property<Guid>("SaleBatchAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseBatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SaleItemId")
                        .HasColumnType("uuid");

                    b.HasKey("SaleBatchAllocationId");

                    b.HasIndex("PurchaseBatchId");

                    b.HasIndex("SaleItemId");

                    b.ToTable("SaleBatchAllocations");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.SaleItem", b =>
                {
                    b.Property<Guid>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("SaleItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.SalesPayment", b =>
                {
                    b.Property<Guid>("SalesPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("SalesPaymentId");

                    b.HasIndex("SaleId");

                    b.ToTable("SalesPayments");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Transportation", b =>
                {
                    b.Property<Guid>("TransportationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RelatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("TransportationId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("Transportations");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.WorkType", b =>
                {
                    b.Property<Guid>("WorkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WorkTypeId");

                    b.ToTable("WorkTypes");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkillType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.WorkerPayment", b =>
                {
                    b.Property<Guid>("WorkerPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PaidStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProcessingStageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkerPaymentId");

                    b.HasIndex("ProcessingStageId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerPayments");
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.BatchOutputAllocation", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.PurchaseBatch", null)
                        .WithMany()
                        .HasForeignKey("PurchaseBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.FinishedInventory", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.PurchaseBatch", null)
                        .WithMany()
                        .HasForeignKey("PurchaseBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingCost", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingOutput", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingRun", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingRunInput", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.PurchaseBatch", null)
                        .WithMany()
                        .HasForeignKey("PurchaseBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingStage", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.WorkType", null)
                        .WithMany()
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.ProcessingStageWorker", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingStage", null)
                        .WithMany()
                        .HasForeignKey("ProcessingStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.PurchaseBatch", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.PurchasePayment", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.PurchaseBatch", null)
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.RawInventory", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.PurchaseBatch", null)
                        .WithMany()
                        .HasForeignKey("PurchaseBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Sale", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Buyer", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.SaleBatchAllocation", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.PurchaseBatch", null)
                        .WithMany()
                        .HasForeignKey("PurchaseBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.SaleItem", null)
                        .WithMany()
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.SaleItem", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.SalesPayment", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.Transportation", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.Location", null)
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Location", null)
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.WorkerPayment", b =>
                {
                    b.HasOne("AgroProcessing.Domain.Entries.ProcessingStage", null)
                        .WithMany()
                        .HasForeignKey("ProcessingStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroProcessing.Domain.Entries.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroProcessing.Domain.Entries.PurchaseBatch", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
